modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="thesevenof__mc"
version="1.0.0"
displayName="TheSevenOf  MC"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="berli, MCreator"

[[dependencies.thesevenof__mc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




